# Generated by Django 5.1 on 2025-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conta", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conta",
            options={"ordering": ["-saldo", "nome"]},
        ),
        migrations.RemoveField(
            model_name="conta",
            name="descricao",
        ),
        migrations.AddField(
            model_name="conta",
            name="nome",
            field=models.CharField(
                default=1, max_length=40, verbose_name="Nome da conta"
            ),
            preserve_default=False,
        ),
    ]
