# Generated by Django 3.0 on 2022-12-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, unique=True, verbose_name='descrição')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
    ]
