# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-08 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_remove_categoria_tipo'),
        ('conta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganhos', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateField()),
                ('categorias', models.ManyToManyField(to='categoria.Categoria')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conta.Conta')),
                ('usuario_lucro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valor', 'ganhos'],
            },
        ),
    ]
