# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-08 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lucro',
            old_name='usuario_lucro',
            new_name='usuario',
        ),
    ]
