# Generated by Django 5.1 on 2024-09-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuario", "0003_auto_20221219_1354"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.AddField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Se True, o usuário pode acessar o admin.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Se ativo o usuário tem permissão para acessar o sistema",
                verbose_name="ativo",
            ),
        ),
    ]
