# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-04 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancamento', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateField()),
                ('categorias', models.ManyToManyField(to='categoria.Categoria')),
            ],
            options={
                'ordering': ['-valor', 'lancamento'],
            },
        ),
    ]
