# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-06 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-valor', 'dispesas']},
        ),
        migrations.RenameField(
            model_name='lancamento',
            old_name='lancamento',
            new_name='dispesas',
        ),
    ]
