# Generated by Django 3.0 on 2022-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('lancamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='categoria.Categoria', verbose_name='Categorias '),
        ),
    ]
