# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-06 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0002_auto_20221206_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-valor', 'dispesa']},
        ),
        migrations.RenameField(
            model_name='lancamento',
            old_name='dispesas',
            new_name='dispesa',
        ),
    ]
