# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-06 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
        ('lancamento', '0004_lancamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conta.Conta'),
        ),
    ]
