# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-07 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0005_lancamento_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
