# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-07 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0006_auto_20221207_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(),
        ),
    ]
