# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-12-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0007_auto_20221207_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conta.Conta'),
        ),
    ]
